theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  # summary:
  #   position: after-hero
  search:
    active: true  
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
  breadcrumb:
    position: after-hero
  menu:
    dropdown:
      linkToLevel1: true